apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: three-tier
type: Opaque
data:
  mongodb-username: dXNlcg==          # base64 for "user"
  mongodb-password: cGFzc3dvcmQ=      # base64 for "password"