apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: three-tier
spec:
  selector:
    role: mongodb           # Does it matter if i have role:mongodb or app:mongodb
  ports:
    - name: mongodb-svc       # Do i need a name here?
      protocol: TCP
      port: 27017
      targetPort: 27017
