version: "3.8"

services:
  mongo:
    image: mongo
    container_name: todo-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - 3000:80 
      # host:container (React is served by Nginx on port 80)
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data: 